### ISSUE TITLE
AttributeError: 'list' object has no attribute 'op'

### ISSUE THREAD

**Issue by gaopenggang** [fuzimaoxinan/Tensorflow_deep-belief-network#2]
gao@ubuntu14:~/py_work/DBN/Tensorflow_deep-belief-network-master/test$ python3 classification_MINST.py 
Extracting ../dataset/MNIST_data/train-images-idx3-ubyte.gz
Extracting ../dataset/MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../dataset/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../dataset/MNIST_data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "classification_MINST.py", line 42, in <module>
    rbm_lr=1e-3)
  File "../models/dbn.py", line 47, in __init__
    self.build_model()
  File "../models/dbn.py", line 89, in build_model
    self.train_batch_bp=_optimization.trainer(algorithm=self.bp_algorithm).minimize(self.loss, var_list=self.parameter_list)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 288, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 346, in compute_gradients
    processors = [_get_processor(v) for v in var_list]
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 346, in <listcomp>
    processors = [_get_processor(v) for v in var_list]
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 115, in _get_processor
    if v.op.type == "ReadVariableOp":
AttributeError: 'list' object has no attribute 'op'
could you tell me how to resolve it? Thanks

**Comment by gaopenggang** [comment]
Thank you so much. It works.

**Comment by fuzimaoxinan** [comment]
I fixed some bug again
